server:
  port: 8777
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ironwilly/config-server
          default-label: main
          search-paths:
          - '"service"'
